### ISSUE TITLE
SetOptions and ExpireOptions should be an interface, not struct

### ISSUE THREAD

**Issue by osteensco** [EchoVault/SugarDB#100]
Disclaimer: This is just a suggestion, I think it's a good idea but I if no one else does I'm not gonna fight super hard for it

**Problem:** 
Currently, in the generic API we define structs to allow users to set expiry and other behaviors for Set, Expire, ExpireAt, PExpire, and PExpireAt methods. Boolean fields are set by the user, but there are no guardrails in place to stop a user from passing in something like ```ExpireOptions{NX: true, LT: true}```. 

I don't think it's a major issue, but I do think that this design could result in users experiencing what they perceive as unexpected behaviors.

**Proposed Solution:**
I know go enums are nonexistent and custom implementation is a bit of a pain point for the language, however, I believe something like this would still be readable and provide a better experience to users.

```go
type ExOpt string

const (
	NX ExOpt = "NX"
	XX ExOpt = "XX"
	LT ExOpt = "LT"
	GT ExOpt = "GT"
)

type ExpireOptions interface {
	IsExOpt() ExOpt
}

func (x ExOpt) IsExOpt() ExOpt { return x }


// to show function arg
func printConsts(str ExpireOptions) {

	fmt.Println(str)
}



``` 

This allows stronger type safety for methods that currently use these structs, and more clear expected behavior for users implementing these methods. Additionally, this provides use of LSPs  (tested with gopls) to discover available constants in the package by navigating to refrence/definition. This coupled with inline documentation should provide a better user experience in my opinion.

https://go.dev/play/p/a3PeonPSbkk

This would require some refactoring on the methods that use these structs, but it would simplify the logic from using switch cases to simply passing the constant into the command.

**Comment by kelvinmwinuka** [comment]
@osteensco I like this approach. If you're interested in implementing this, I'd happily add it.

**Comment by osteensco** [comment]
sounds good, I'll work on a PR for this, thanks!
