### ISSUE TITLE
Implement COPY command

### ISSUE THREAD

**Issue by kelvinmwinuka** [EchoVault/SugarDB#111]
Copies value from one key to another.
Reference: https://redis.io/docs/latest/commands/copy/

## Client-Server Spec:

Command File: ./internal/modules/generic/commands.go
Test File: ./internal/modules/generic/commands_test.go

Command: `copy`
Module: `constants.GenericModule`
Categories:  `contants.GenericCategory`, `constants.WriteCategory`, `constants.SlowCategory`
Description: `(COPY source destination [DB destination-db] [REPLACE]) copies a value from one key to another`
Sync: `true`

## Embedded Spec:

Command File: ./echovault/api_generic.go
Test File: ./echovault/api_generic_test.go

## Documentation

Add documentation to `./docs/docs/commands/generic/copy.mdx`

**Comment by zenc0derr** [comment]
Working on this.
