### ISSUE TITLE
Implement MOVE command

### ISSUE THREAD

**Issue by kelvinmwinuka** [EchoVault/SugarDB#112]
Moves a key from the selected database to the specified database.
Reference: https://redis.io/docs/latest/commands/move/

## Client-Server Spec:

Command File: ./internal/modules/generic/commands.go
Test File: ./internal/modules/generic/commands_test.go

Command: `move`
Module: `constants.GenericModule`
Categories:  `contants.KeyspaceCategory`, `constants.WriteCategory`, `constants.FastCategory`
Description: `(MOVE key db) Moves a key from the selected database to the specified database.`
Sync: `true`

## Embedded Spec:

Command File: ./echovault/api_generic.go
Test File: ./echovault/api_generic_test.go

## Documentation

Add documentation to `./docs/docs/commands/generic/move.mdx`

**Comment by osteensco** [comment]
I'll take this one.
