### ISSUE TITLE
Add documentation for HMGET command

### ISSUE THREAD

**Issue by kelvinmwinuka** [EchoVault/SugarDB#119]
- Add documentation for the implemented HMGET command to `docs/docs/commands/hash/HMGET.mdx`
- Add link to the command's documentation in README.md

## Client-Server Spec:

Command File: ./internal/modules/hash/commands.go
Test File: ./internal/modules/hash/commands_test.go

## Embedded Spec:

Command File: ./echovault/api_hash.go
Test File: ./echovault/api_hash_test.go

**Comment by thesambayo** [comment]
@kelvinmwinuka, picking up this issue
