### ISSUE TITLE
Create script to benchmark against Redis

### ISSUE THREAD

**Issue by kelvinmwinuka** [EchoVault/SugarDB#125]
Although we have some performance benchmarks in the README, we need to create a benchmark comparison with Redis.

## Proposal
- Create a script that can be triggered from the makefile.
- The script should use redis-benchmark to test EchoVault and Redis.
- Create a comparison chart or table for each commands tested.
- Benchmark embedded EchoVault as well.

**Comment by NicoleStrel** [comment]
@kelvinmwinuka hey, I'll work on this if its free
