### ISSUE TITLE
Cannot use SugarDB as Embedded 

### ISSUE THREAD

**Issue by jasoet** [EchoVault/SugarDB#154]
I want to run SugarDB as Embedded Database and follow the Readme, but it doesn't work.

Add this to my `go.mod` 
`github.com/echovault/sugardb v0.16.0
`

But then We cannot find the import statement on the code 

```
import github.com/echovault/sugardb // Doesn't Work

func main() {
  server, err := sugardb.NewSugarDB()
  if err != nil {
    log.Fatal(err)
  }

  _, _, _ = server.Set("key", "Hello, SugarDB!", sugardb.SETOptions{})

  v, _ := server.Get("key")
  fmt.Println(v) // Hello, SugarDB!

  // (Optional): Listen for TCP connections on this SugarDB instance.
  server.Start()
}
```

**Comment by kelvinmwinuka** [comment]
Hi @jasoet,

I think there's some confusion about the import package name. It should be `github.com/echovault/sugardb/sugardb`

**Comment by jasoet** [comment]
@kelvinmwinuka 
Thanks its works now.
