### ISSUE TITLE
Implement RENAMENX command

### ISSUE THREAD

**Issue by kelvinmwinuka** [EchoVault/SugarDB#59]
Implement the RENAMENX command, which renames the specified key with the new name only if the new keyname does not already exist. 
Reference: https://redis.io/docs/latest/commands/renamenx/

## Client-Server Spec:

Command File: ./internal/modules/generic/commands.go
Test File: ./internal/modules/generic/commands_test.go

Command: `renamenx`
Module: `constants.GenericModule`
Categories: `constants.KeyspaceCategory`, `constants.WriteCategory`, `constants.FastCategory`
Description: `(RENAMENX key newkey) Renames the specified key with the new name only if the new name does not already exist.`
Sync: `true`

## Embedded Spec:

Command File: ./echovault/api_generic.go
Test File: ./echovault/api_generic_test.go

NOTE: You may have to edit the `HandlerFuncParams` type to include a function that renames keys. Alternatively, you could use the `GetValues`, `DeleteKeys` and `SetValues` methods together to delete the old key and set a new key with the old value. The first approach would be more atomic though.

At the moment, only replication clusters exist without sharding. So the key should be renames across the entire cluster.

**Comment by DMcP89** [comment]
@kelvinmwinuka I'll take this one
